# Protocol the application layer uses to talk to the outside world,
# implemented in infrastructure/. This is what keeps application/ free of a
# direct SQLAlchemy import, same convention as the other services.

from __future__ import annotations

from types import TracebackType
from typing import Protocol
from uuid import UUID

from app.domain.entities import Notification, NotificationPage


class NotificationRepository(Protocol):
    async def get_by_id(self, notification_id: UUID) -> Notification | None: ...
    # Newest first, a slice of the tray plus how many there are in total
    # and how many are still unread.
    async def list_page(self, recipient_id: UUID, recipient_role: str, offset: int, limit: int) -> NotificationPage: ...
    async def add(self, notification: Notification) -> None: ...
    async def mark_read(self, notification: Notification) -> None: ...
    async def delete(self, notification_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    @property
    def notifications(self) -> NotificationRepository: ...

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
