"""Protocols the application layer uses to talk to the outside world,
implemented in infrastructure/. This is what keeps application/ free of
direct SQLAlchemy, jose or bcrypt imports."""

from __future__ import annotations

from types import TracebackType
from typing import Protocol
from uuid import UUID

from app.domain.entities import Consent, DocumentType, Guardian, Person, RelationshipType, Student, Teacher


class PersonRepository(Protocol):
    async def get_by_email(self, email: str) -> Person | None: ...
    async def get_by_id(self, person_id: UUID) -> Person | None: ...
    async def get_by_document_number(self, document_number: str) -> Person | None: ...
    async def add(self, person: Person) -> None: ...


class GuardianRepository(Protocol):
    async def get_by_person_id(self, person_id: UUID) -> Guardian | None: ...
    async def get_by_id(self, guardian_id: UUID) -> Guardian | None: ...
    async def add(self, guardian: Guardian) -> None: ...
    async def delete(self, guardian_id: UUID) -> None: ...


class TeacherRepository(Protocol):
    async def get_by_person_id(self, person_id: UUID) -> Teacher | None: ...
    async def get_by_id(self, teacher_id: UUID) -> Teacher | None: ...
    async def add(self, teacher: Teacher) -> None: ...


class StudentRepository(Protocol):
    async def get_by_id(self, student_id: UUID) -> Student | None: ...
    async def list_by_guardian(self, guardian_id: UUID) -> list[Student]: ...
    async def add(self, student: Student) -> None: ...
    async def update_avatar(self, student_id: UUID, avatar: str) -> None: ...


class ConsentRepository(Protocol):
    async def add(self, consent: Consent) -> None: ...


class DocumentTypeRepository(Protocol):
    async def list_all(self) -> list[DocumentType]: ...
    async def get_by_id(self, document_type_id: int) -> DocumentType | None: ...


class RelationshipTypeRepository(Protocol):
    async def list_all(self) -> list[RelationshipType]: ...
    async def get_by_id(self, relationship_type_id: int) -> RelationshipType | None: ...


class UnitOfWork(Protocol):
    @property
    def people(self) -> PersonRepository: ...

    @property
    def guardians(self) -> GuardianRepository: ...

    @property
    def teachers(self) -> TeacherRepository: ...

    @property
    def students(self) -> StudentRepository: ...

    @property
    def consents(self) -> ConsentRepository: ...

    @property
    def document_types(self) -> DocumentTypeRepository: ...

    @property
    def relationship_types(self) -> RelationshipTypeRepository: ...

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def flush(self) -> None:
        """Sends pending INSERT/UPDATE statements to the DB without closing the
        transaction. Needed between FK-related entities built with a plain id
        instead of an ORM object graph. Without it, automatic flush order
        between them isn't guaranteed."""
        ...


class PasswordHasher(Protocol):
    def hash(self, valor_plano: str) -> str: ...
    def verificar(self, valor_plano: str, hash_guardado: str) -> bool: ...

    @property
    def dummy_hash(self) -> str:
        """A precomputed hash that never matches a real password or PIN, used to
        keep a failed login's timing constant when there's no real hash to check
        against (see AuthService.login)."""
        ...


class TokenIssuer(Protocol):
    def emitir_access_token(self, subject_id: UUID, role: str, extra: dict[str, str]) -> str: ...
    def emitir_refresh_token(self, subject_id: UUID, role: str) -> tuple[str, str]:
        """Returns (token, jti). The jti lets logout invalidate it later.
        subject_id is person_id for guardian/teacher, and student_id for a
        student profile, since Student isn't a Person in this model."""
        ...

    def decodificar(self, token: str) -> dict[str, object]: ...


class RateLimiter(Protocol):
    async def permitir(self, clave: str, maximo: int, ventana_seg: int) -> bool:
        """Increments the counter for clave and returns False once it passes
        maximo within the window."""
        ...


class TokenBlacklist(Protocol):
    async def invalidar(self, jti: str, ttl_seg: int) -> None: ...
    async def esta_invalidado(self, jti: str) -> bool: ...
