# Protocols the application layer uses to talk to the outside world,
# implemented in infrastructure/. This is what keeps application/ free of
# direct SQLAlchemy, boto3, httpx or redis imports.

from __future__ import annotations

from types import TracebackType
from typing import Protocol
from uuid import UUID

from app.domain.entities import Classroom, Enrollment, SignedDownload, StudentInfo, UserClaims


class ClassroomRepository(Protocol):
    async def get_by_id(self, classroom_id: UUID) -> Classroom | None: ...
    async def get_by_code(self, enrollment_code: str) -> Classroom | None: ...
    async def list_by_teacher(self, teacher_id: UUID) -> list[Classroom]: ...
    async def list_by_ids(self, classroom_ids: list[UUID]) -> list[Classroom]: ...
    async def add(self, classroom: Classroom) -> None: ...
    async def update(self, classroom: Classroom) -> None: ...
    # Its enrollments go with it (cascade).
    async def delete(self, classroom_id: UUID) -> None: ...


class EnrollmentRepository(Protocol):
    async def get_by_id(self, enrollment_id: UUID) -> Enrollment | None: ...
    async def get_by_student_and_classroom(self, student_id: UUID, classroom_id: UUID) -> Enrollment | None: ...
    async def list_pending_by_classroom(self, classroom_id: UUID) -> list[Enrollment]: ...
    async def list_accepted_by_classroom(self, classroom_id: UUID) -> list[Enrollment]: ...
    async def list_accepted_by_student(self, student_id: UUID) -> list[Enrollment]: ...
    # How many pending requests each of these classrooms has, in one query.
    # A classroom with none isn't in the result.
    async def count_pending_by_classrooms(self, classroom_ids: list[UUID]) -> dict[UUID, int]: ...
    async def add(self, enrollment: Enrollment) -> None: ...
    async def update(self, enrollment: Enrollment) -> None: ...
    async def delete(self, enrollment_id: UUID) -> None: ...


class UnitOfWork(Protocol):
    @property
    def classrooms(self) -> ClassroomRepository: ...

    @property
    def enrollments(self) -> EnrollmentRepository: ...

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: TracebackType | None
    ) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


# The bucket is private: nothing in it has a public URL. Files only reach
# the browser through an endpoint of this service that checks access first.
class ObjectStorage(Protocol):
    async def upload(self, key: str, content: bytes, content_type: str) -> None: ...

    # Signs a GET of the key for Caddy (see app/api/media.py). No network
    # call: if the file is missing, Garage answers 404 when Caddy asks.
    def sign_download(self, key: str) -> SignedDownload: ...

    # Does nothing if the key is already gone.
    async def delete(self, key: str) -> None: ...


class EventPublisher(Protocol):
    async def publicar(self, canal: str, evento: dict[str, object]) -> None: ...


class RateLimiter(Protocol):
    # Increments the counter for clave and returns False once it passes
    # maximo within the window.
    async def permitir(self, clave: str, maximo: int, ventana_seg: int) -> bool: ...


# Client for content-service's internal routes. The production one has a
# timeout and a circuit breaker, like the identity-service client.
class ContentGateway(Protocol):
    # Deletes every lesson of the classroom, with its blocks and images.
    async def delete_classroom_lessons(self, classroom_id: UUID) -> None: ...


# Client for identity-service. The production implementation
# (infrastructure/http_clients/identity_client.py) wraps calls with a 2s
# timeout plus a circuit breaker. Tests inject an in-memory double via
# dependency_overrides.
class IdentityGateway(Protocol):
    async def validar_token(self, access_token: str, renew: bool = True) -> UserClaims: ...
    async def obtener_estudiante(self, student_id: UUID) -> StudentInfo: ...
    # "Nombres Apellidos" of a teacher, for the notifications.
    async def obtener_nombre_docente(self, teacher_id: UUID) -> str: ...
